#############################################################################
# Makefile for building: kr_ccpilot_va
# Generated by qmake (3.0) (Qt 5.6.3)
# Project:  kr_ccpilot_va.pro
# Template: app
# Command: /opt/VA/Qt-5.6.3/bin/qmake -spec linux-arm-none-gnueabi-g++ CONFIG+=debug CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile kr_ccpilot_va.pro
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = arm-none-linux-gnueabi-gcc
CXX           = arm-none-linux-gnueabi-g++
DEFINES       = -DLINUX -DCCAUX -DQT_QML_DEBUG -DQT_DECLARATIVE_DEBUG -DQT_QUICK_LIB -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_QML_LIB -DQT_NETWORK_LIB -DQT_CORE_LIB
CFLAGS        = -pipe -O3 -march=armv7-a -mtune=cortex-a8 -mfpu=neon -mfloat-abi=softfp -g -Wall -W -D_REENTRANT -fPIC $(DEFINES)
CXXFLAGS      = -pipe -O3 -march=armv7-a -mtune=cortex-a8 -mfpu=neon -mfloat-abi=softfp -Wno-psabi -g -std=gnu++0x -Wall -W -D_REENTRANT -fPIC $(DEFINES)
INCPATH       = -I. -I/opt/VA/Qt-5.6.3/include -I/opt/VA/Qt-5.6.3/include/QtQuick -I/opt/VA/Qt-5.6.3/include/QtWidgets -I/opt/VA/Qt-5.6.3/include/QtGui -I/opt/VA/Qt-5.6.3/include/QtQml -I/opt/VA/Qt-5.6.3/include/QtNetwork -I/opt/VA/Qt-5.6.3/include/QtCore -I. -I/opt/VA/usr/include -I/opt/VA/Qt-5.6.3/mkspecs/linux-arm-none-gnueabi-g++
QMAKE         = /opt/VA/Qt-5.6.3/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = kr_ccpilot_va1.0.0
DISTDIR = /home/ccs/qt/MyProjects/kr_ccpilot_va/.tmp/kr_ccpilot_va1.0.0
LINK          = arm-none-linux-gnueabi-g++
LFLAGS        = -Wl,-rpath-link,/opt/VA/usr/lib -Wl,-rpath,/opt/VA/Qt-5.6.3/lib
LIBS          = $(SUBLIBS) -L/opt/VA/usr/lib -L/opt/VA/Qt-5.6.3/lib -lQt5Quick -lQt5Widgets -lQt5Gui -lQt5Qml -lQt5Network -lQt5Core -lGLESv2 -lOpenVG -lEGL -lpthread 
AR            = arm-none-linux-gnueabi-ar cqs
RANLIB        = 
SED           = sed
STRIP         = arm-none-linux-gnueabi-strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		pulu.cpp qrc_qml.cpp \
		moc_pulu.cpp
OBJECTS       = main.o \
		pulu.o \
		qrc_qml.o \
		moc_pulu.o
DIST          = /opt/VA/Qt-5.6.3/mkspecs/features/spec_pre.prf \
		/opt/VA/Qt-5.6.3/mkspecs/common/unix.conf \
		/opt/VA/Qt-5.6.3/mkspecs/common/linux.conf \
		/opt/VA/Qt-5.6.3/mkspecs/common/sanitize.conf \
		/opt/VA/Qt-5.6.3/mkspecs/common/gcc-base.conf \
		/opt/VA/Qt-5.6.3/mkspecs/common/gcc-base-unix.conf \
		/opt/VA/Qt-5.6.3/mkspecs/common/g++-base.conf \
		/opt/VA/Qt-5.6.3/mkspecs/common/g++-unix.conf \
		/opt/VA/Qt-5.6.3/mkspecs/qconfig.pri \
		/opt/VA/Qt-5.6.3/mkspecs/modules/qt_lib_3dcore.pri \
		/opt/VA/Qt-5.6.3/mkspecs/modules/qt_lib_3dcore_private.pri \
		/opt/VA/Qt-5.6.3/mkspecs/modules/qt_lib_3dinput.pri \
		/opt/VA/Qt-5.6.3/mkspecs/modules/qt_lib_3dinput_private.pri \
		/opt/VA/Qt-5.6.3/mkspecs/modules/qt_lib_3dlogic.pri \
		/opt/VA/Qt-5.6.3/mkspecs/modules/qt_lib_3dlogic_private.pri \
		/opt/VA/Qt-5.6.3/mkspecs/modules/qt_lib_3dquick.pri \
		/opt/VA/Qt-5.6.3/mkspecs/modules/qt_lib_3dquick_private.pri \
		/opt/VA/Qt-5.6.3/mkspecs/modules/qt_lib_3dquickinput.pri \
		/opt/VA/Qt-5.6.3/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		/opt/VA/Qt-5.6.3/mkspecs/modules/qt_lib_3dquickrender.pri \
		/opt/VA/Qt-5.6.3/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		/opt/VA/Qt-5.6.3/mkspecs/modules/qt_lib_3drender.pri \
		/opt/VA/Qt-5.6.3/mkspecs/modules/qt_lib_3drender_private.pri \
		/opt/VA/Qt-5.6.3/mkspecs/modules/qt_lib_bluetooth.pri \
		/opt/VA/Qt-5.6.3/mkspecs/modules/qt_lib_bluetooth_private.pri \
		/opt/VA/Qt-5.6.3/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/opt/VA/Qt-5.6.3/mkspecs/modules/qt_lib_clucene_private.pri \
		/opt/VA/Qt-5.6.3/mkspecs/modules/qt_lib_concurrent.pri \
		/opt/VA/Qt-5.6.3/mkspecs/modules/qt_lib_concurrent_private.pri \
		/opt/VA/Qt-5.6.3/mkspecs/modules/qt_lib_core.pri \
		/opt/VA/Qt-5.6.3/mkspecs/modules/qt_lib_core_private.pri \
		/opt/VA/Qt-5.6.3/mkspecs/modules/qt_lib_dbus.pri \
		/opt/VA/Qt-5.6.3/mkspecs/modules/qt_lib_dbus_private.pri \
		/opt/VA/Qt-5.6.3/mkspecs/modules/qt_lib_eglfs_device_lib_private.pri \
		/opt/VA/Qt-5.6.3/mkspecs/modules/qt_lib_enginio.pri \
		/opt/VA/Qt-5.6.3/mkspecs/modules/qt_lib_enginio_private.pri \
		/opt/VA/Qt-5.6.3/mkspecs/modules/qt_lib_gui.pri \
		/opt/VA/Qt-5.6.3/mkspecs/modules/qt_lib_gui_private.pri \
		/opt/VA/Qt-5.6.3/mkspecs/modules/qt_lib_help.pri \
		/opt/VA/Qt-5.6.3/mkspecs/modules/qt_lib_help_private.pri \
		/opt/VA/Qt-5.6.3/mkspecs/modules/qt_lib_labscontrols_private.pri \
		/opt/VA/Qt-5.6.3/mkspecs/modules/qt_lib_labstemplates_private.pri \
		/opt/VA/Qt-5.6.3/mkspecs/modules/qt_lib_location.pri \
		/opt/VA/Qt-5.6.3/mkspecs/modules/qt_lib_location_private.pri \
		/opt/VA/Qt-5.6.3/mkspecs/modules/qt_lib_multimedia.pri \
		/opt/VA/Qt-5.6.3/mkspecs/modules/qt_lib_multimedia_private.pri \
		/opt/VA/Qt-5.6.3/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/opt/VA/Qt-5.6.3/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/opt/VA/Qt-5.6.3/mkspecs/modules/qt_lib_network.pri \
		/opt/VA/Qt-5.6.3/mkspecs/modules/qt_lib_network_private.pri \
		/opt/VA/Qt-5.6.3/mkspecs/modules/qt_lib_nfc.pri \
		/opt/VA/Qt-5.6.3/mkspecs/modules/qt_lib_nfc_private.pri \
		/opt/VA/Qt-5.6.3/mkspecs/modules/qt_lib_opengl.pri \
		/opt/VA/Qt-5.6.3/mkspecs/modules/qt_lib_opengl_private.pri \
		/opt/VA/Qt-5.6.3/mkspecs/modules/qt_lib_openglextensions.pri \
		/opt/VA/Qt-5.6.3/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/opt/VA/Qt-5.6.3/mkspecs/modules/qt_lib_platformsupport_private.pri \
		/opt/VA/Qt-5.6.3/mkspecs/modules/qt_lib_positioning.pri \
		/opt/VA/Qt-5.6.3/mkspecs/modules/qt_lib_positioning_private.pri \
		/opt/VA/Qt-5.6.3/mkspecs/modules/qt_lib_printsupport.pri \
		/opt/VA/Qt-5.6.3/mkspecs/modules/qt_lib_printsupport_private.pri \
		/opt/VA/Qt-5.6.3/mkspecs/modules/qt_lib_qml.pri \
		/opt/VA/Qt-5.6.3/mkspecs/modules/qt_lib_qml_private.pri \
		/opt/VA/Qt-5.6.3/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/opt/VA/Qt-5.6.3/mkspecs/modules/qt_lib_qmltest.pri \
		/opt/VA/Qt-5.6.3/mkspecs/modules/qt_lib_qmltest_private.pri \
		/opt/VA/Qt-5.6.3/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		/opt/VA/Qt-5.6.3/mkspecs/modules/qt_lib_quick.pri \
		/opt/VA/Qt-5.6.3/mkspecs/modules/qt_lib_quick_private.pri \
		/opt/VA/Qt-5.6.3/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/opt/VA/Qt-5.6.3/mkspecs/modules/qt_lib_quickwidgets.pri \
		/opt/VA/Qt-5.6.3/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/opt/VA/Qt-5.6.3/mkspecs/modules/qt_lib_script.pri \
		/opt/VA/Qt-5.6.3/mkspecs/modules/qt_lib_script_private.pri \
		/opt/VA/Qt-5.6.3/mkspecs/modules/qt_lib_scripttools.pri \
		/opt/VA/Qt-5.6.3/mkspecs/modules/qt_lib_scripttools_private.pri \
		/opt/VA/Qt-5.6.3/mkspecs/modules/qt_lib_sensors.pri \
		/opt/VA/Qt-5.6.3/mkspecs/modules/qt_lib_sensors_private.pri \
		/opt/VA/Qt-5.6.3/mkspecs/modules/qt_lib_serialport.pri \
		/opt/VA/Qt-5.6.3/mkspecs/modules/qt_lib_serialport_private.pri \
		/opt/VA/Qt-5.6.3/mkspecs/modules/qt_lib_sql.pri \
		/opt/VA/Qt-5.6.3/mkspecs/modules/qt_lib_sql_private.pri \
		/opt/VA/Qt-5.6.3/mkspecs/modules/qt_lib_svg.pri \
		/opt/VA/Qt-5.6.3/mkspecs/modules/qt_lib_svg_private.pri \
		/opt/VA/Qt-5.6.3/mkspecs/modules/qt_lib_testlib.pri \
		/opt/VA/Qt-5.6.3/mkspecs/modules/qt_lib_testlib_private.pri \
		/opt/VA/Qt-5.6.3/mkspecs/modules/qt_lib_uiplugin.pri \
		/opt/VA/Qt-5.6.3/mkspecs/modules/qt_lib_uitools.pri \
		/opt/VA/Qt-5.6.3/mkspecs/modules/qt_lib_uitools_private.pri \
		/opt/VA/Qt-5.6.3/mkspecs/modules/qt_lib_webchannel.pri \
		/opt/VA/Qt-5.6.3/mkspecs/modules/qt_lib_webchannel_private.pri \
		/opt/VA/Qt-5.6.3/mkspecs/modules/qt_lib_websockets.pri \
		/opt/VA/Qt-5.6.3/mkspecs/modules/qt_lib_websockets_private.pri \
		/opt/VA/Qt-5.6.3/mkspecs/modules/qt_lib_widgets.pri \
		/opt/VA/Qt-5.6.3/mkspecs/modules/qt_lib_widgets_private.pri \
		/opt/VA/Qt-5.6.3/mkspecs/modules/qt_lib_xml.pri \
		/opt/VA/Qt-5.6.3/mkspecs/modules/qt_lib_xml_private.pri \
		/opt/VA/Qt-5.6.3/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/opt/VA/Qt-5.6.3/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		/opt/VA/Qt-5.6.3/mkspecs/modules/qt_lib_zlib_private.pri \
		/opt/VA/Qt-5.6.3/mkspecs/features/qt_functions.prf \
		/opt/VA/Qt-5.6.3/mkspecs/features/qt_config.prf \
		/opt/VA/Qt-5.6.3/mkspecs/linux-arm-none-gnueabi-g++/qmake.conf \
		/opt/VA/Qt-5.6.3/mkspecs/features/spec_post.prf \
		/opt/VA/Qt-5.6.3/mkspecs/features/exclusive_builds.prf \
		/opt/VA/Qt-5.6.3/mkspecs/features/default_pre.prf \
		deployment.pri \
		/opt/VA/Qt-5.6.3/mkspecs/features/resolve_config.prf \
		/opt/VA/Qt-5.6.3/mkspecs/features/default_post.prf \
		/opt/VA/Qt-5.6.3/mkspecs/features/qml_debug.prf \
		/opt/VA/Qt-5.6.3/mkspecs/features/declarative_debug.prf \
		/opt/VA/Qt-5.6.3/mkspecs/features/warn_on.prf \
		/opt/VA/Qt-5.6.3/mkspecs/features/qt.prf \
		/opt/VA/Qt-5.6.3/mkspecs/features/resources.prf \
		/opt/VA/Qt-5.6.3/mkspecs/features/moc.prf \
		/opt/VA/Qt-5.6.3/mkspecs/features/unix/opengl.prf \
		/opt/VA/Qt-5.6.3/mkspecs/features/uic.prf \
		/opt/VA/Qt-5.6.3/mkspecs/features/unix/thread.prf \
		/opt/VA/Qt-5.6.3/mkspecs/features/file_copies.prf \
		/opt/VA/Qt-5.6.3/mkspecs/features/testcase_targets.prf \
		/opt/VA/Qt-5.6.3/mkspecs/features/exceptions.prf \
		/opt/VA/Qt-5.6.3/mkspecs/features/yacc.prf \
		/opt/VA/Qt-5.6.3/mkspecs/features/lex.prf \
		kr_ccpilot_va.pro pulu.h main.cpp \
		pulu.cpp
QMAKE_TARGET  = kr_ccpilot_va
DESTDIR       = 
TARGET        = kr_ccpilot_va


first: all
####### Build rules

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: kr_ccpilot_va.pro /opt/VA/Qt-5.6.3/mkspecs/linux-arm-none-gnueabi-g++/qmake.conf /opt/VA/Qt-5.6.3/mkspecs/features/spec_pre.prf \
		/opt/VA/Qt-5.6.3/mkspecs/common/unix.conf \
		/opt/VA/Qt-5.6.3/mkspecs/common/linux.conf \
		/opt/VA/Qt-5.6.3/mkspecs/common/sanitize.conf \
		/opt/VA/Qt-5.6.3/mkspecs/common/gcc-base.conf \
		/opt/VA/Qt-5.6.3/mkspecs/common/gcc-base-unix.conf \
		/opt/VA/Qt-5.6.3/mkspecs/common/g++-base.conf \
		/opt/VA/Qt-5.6.3/mkspecs/common/g++-unix.conf \
		/opt/VA/Qt-5.6.3/mkspecs/qconfig.pri \
		/opt/VA/Qt-5.6.3/mkspecs/modules/qt_lib_3dcore.pri \
		/opt/VA/Qt-5.6.3/mkspecs/modules/qt_lib_3dcore_private.pri \
		/opt/VA/Qt-5.6.3/mkspecs/modules/qt_lib_3dinput.pri \
		/opt/VA/Qt-5.6.3/mkspecs/modules/qt_lib_3dinput_private.pri \
		/opt/VA/Qt-5.6.3/mkspecs/modules/qt_lib_3dlogic.pri \
		/opt/VA/Qt-5.6.3/mkspecs/modules/qt_lib_3dlogic_private.pri \
		/opt/VA/Qt-5.6.3/mkspecs/modules/qt_lib_3dquick.pri \
		/opt/VA/Qt-5.6.3/mkspecs/modules/qt_lib_3dquick_private.pri \
		/opt/VA/Qt-5.6.3/mkspecs/modules/qt_lib_3dquickinput.pri \
		/opt/VA/Qt-5.6.3/mkspecs/modules/qt_lib_3dquickinput_private.pri \
		/opt/VA/Qt-5.6.3/mkspecs/modules/qt_lib_3dquickrender.pri \
		/opt/VA/Qt-5.6.3/mkspecs/modules/qt_lib_3dquickrender_private.pri \
		/opt/VA/Qt-5.6.3/mkspecs/modules/qt_lib_3drender.pri \
		/opt/VA/Qt-5.6.3/mkspecs/modules/qt_lib_3drender_private.pri \
		/opt/VA/Qt-5.6.3/mkspecs/modules/qt_lib_bluetooth.pri \
		/opt/VA/Qt-5.6.3/mkspecs/modules/qt_lib_bluetooth_private.pri \
		/opt/VA/Qt-5.6.3/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/opt/VA/Qt-5.6.3/mkspecs/modules/qt_lib_clucene_private.pri \
		/opt/VA/Qt-5.6.3/mkspecs/modules/qt_lib_concurrent.pri \
		/opt/VA/Qt-5.6.3/mkspecs/modules/qt_lib_concurrent_private.pri \
		/opt/VA/Qt-5.6.3/mkspecs/modules/qt_lib_core.pri \
		/opt/VA/Qt-5.6.3/mkspecs/modules/qt_lib_core_private.pri \
		/opt/VA/Qt-5.6.3/mkspecs/modules/qt_lib_dbus.pri \
		/opt/VA/Qt-5.6.3/mkspecs/modules/qt_lib_dbus_private.pri \
		/opt/VA/Qt-5.6.3/mkspecs/modules/qt_lib_eglfs_device_lib_private.pri \
		/opt/VA/Qt-5.6.3/mkspecs/modules/qt_lib_enginio.pri \
		/opt/VA/Qt-5.6.3/mkspecs/modules/qt_lib_enginio_private.pri \
		/opt/VA/Qt-5.6.3/mkspecs/modules/qt_lib_gui.pri \
		/opt/VA/Qt-5.6.3/mkspecs/modules/qt_lib_gui_private.pri \
		/opt/VA/Qt-5.6.3/mkspecs/modules/qt_lib_help.pri \
		/opt/VA/Qt-5.6.3/mkspecs/modules/qt_lib_help_private.pri \
		/opt/VA/Qt-5.6.3/mkspecs/modules/qt_lib_labscontrols_private.pri \
		/opt/VA/Qt-5.6.3/mkspecs/modules/qt_lib_labstemplates_private.pri \
		/opt/VA/Qt-5.6.3/mkspecs/modules/qt_lib_location.pri \
		/opt/VA/Qt-5.6.3/mkspecs/modules/qt_lib_location_private.pri \
		/opt/VA/Qt-5.6.3/mkspecs/modules/qt_lib_multimedia.pri \
		/opt/VA/Qt-5.6.3/mkspecs/modules/qt_lib_multimedia_private.pri \
		/opt/VA/Qt-5.6.3/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/opt/VA/Qt-5.6.3/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/opt/VA/Qt-5.6.3/mkspecs/modules/qt_lib_network.pri \
		/opt/VA/Qt-5.6.3/mkspecs/modules/qt_lib_network_private.pri \
		/opt/VA/Qt-5.6.3/mkspecs/modules/qt_lib_nfc.pri \
		/opt/VA/Qt-5.6.3/mkspecs/modules/qt_lib_nfc_private.pri \
		/opt/VA/Qt-5.6.3/mkspecs/modules/qt_lib_opengl.pri \
		/opt/VA/Qt-5.6.3/mkspecs/modules/qt_lib_opengl_private.pri \
		/opt/VA/Qt-5.6.3/mkspecs/modules/qt_lib_openglextensions.pri \
		/opt/VA/Qt-5.6.3/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/opt/VA/Qt-5.6.3/mkspecs/modules/qt_lib_platformsupport_private.pri \
		/opt/VA/Qt-5.6.3/mkspecs/modules/qt_lib_positioning.pri \
		/opt/VA/Qt-5.6.3/mkspecs/modules/qt_lib_positioning_private.pri \
		/opt/VA/Qt-5.6.3/mkspecs/modules/qt_lib_printsupport.pri \
		/opt/VA/Qt-5.6.3/mkspecs/modules/qt_lib_printsupport_private.pri \
		/opt/VA/Qt-5.6.3/mkspecs/modules/qt_lib_qml.pri \
		/opt/VA/Qt-5.6.3/mkspecs/modules/qt_lib_qml_private.pri \
		/opt/VA/Qt-5.6.3/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/opt/VA/Qt-5.6.3/mkspecs/modules/qt_lib_qmltest.pri \
		/opt/VA/Qt-5.6.3/mkspecs/modules/qt_lib_qmltest_private.pri \
		/opt/VA/Qt-5.6.3/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		/opt/VA/Qt-5.6.3/mkspecs/modules/qt_lib_quick.pri \
		/opt/VA/Qt-5.6.3/mkspecs/modules/qt_lib_quick_private.pri \
		/opt/VA/Qt-5.6.3/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/opt/VA/Qt-5.6.3/mkspecs/modules/qt_lib_quickwidgets.pri \
		/opt/VA/Qt-5.6.3/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/opt/VA/Qt-5.6.3/mkspecs/modules/qt_lib_script.pri \
		/opt/VA/Qt-5.6.3/mkspecs/modules/qt_lib_script_private.pri \
		/opt/VA/Qt-5.6.3/mkspecs/modules/qt_lib_scripttools.pri \
		/opt/VA/Qt-5.6.3/mkspecs/modules/qt_lib_scripttools_private.pri \
		/opt/VA/Qt-5.6.3/mkspecs/modules/qt_lib_sensors.pri \
		/opt/VA/Qt-5.6.3/mkspecs/modules/qt_lib_sensors_private.pri \
		/opt/VA/Qt-5.6.3/mkspecs/modules/qt_lib_serialport.pri \
		/opt/VA/Qt-5.6.3/mkspecs/modules/qt_lib_serialport_private.pri \
		/opt/VA/Qt-5.6.3/mkspecs/modules/qt_lib_sql.pri \
		/opt/VA/Qt-5.6.3/mkspecs/modules/qt_lib_sql_private.pri \
		/opt/VA/Qt-5.6.3/mkspecs/modules/qt_lib_svg.pri \
		/opt/VA/Qt-5.6.3/mkspecs/modules/qt_lib_svg_private.pri \
		/opt/VA/Qt-5.6.3/mkspecs/modules/qt_lib_testlib.pri \
		/opt/VA/Qt-5.6.3/mkspecs/modules/qt_lib_testlib_private.pri \
		/opt/VA/Qt-5.6.3/mkspecs/modules/qt_lib_uiplugin.pri \
		/opt/VA/Qt-5.6.3/mkspecs/modules/qt_lib_uitools.pri \
		/opt/VA/Qt-5.6.3/mkspecs/modules/qt_lib_uitools_private.pri \
		/opt/VA/Qt-5.6.3/mkspecs/modules/qt_lib_webchannel.pri \
		/opt/VA/Qt-5.6.3/mkspecs/modules/qt_lib_webchannel_private.pri \
		/opt/VA/Qt-5.6.3/mkspecs/modules/qt_lib_websockets.pri \
		/opt/VA/Qt-5.6.3/mkspecs/modules/qt_lib_websockets_private.pri \
		/opt/VA/Qt-5.6.3/mkspecs/modules/qt_lib_widgets.pri \
		/opt/VA/Qt-5.6.3/mkspecs/modules/qt_lib_widgets_private.pri \
		/opt/VA/Qt-5.6.3/mkspecs/modules/qt_lib_xml.pri \
		/opt/VA/Qt-5.6.3/mkspecs/modules/qt_lib_xml_private.pri \
		/opt/VA/Qt-5.6.3/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/opt/VA/Qt-5.6.3/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		/opt/VA/Qt-5.6.3/mkspecs/modules/qt_lib_zlib_private.pri \
		/opt/VA/Qt-5.6.3/mkspecs/features/qt_functions.prf \
		/opt/VA/Qt-5.6.3/mkspecs/features/qt_config.prf \
		/opt/VA/Qt-5.6.3/mkspecs/linux-arm-none-gnueabi-g++/qmake.conf \
		/opt/VA/Qt-5.6.3/mkspecs/features/spec_post.prf \
		/opt/VA/Qt-5.6.3/mkspecs/features/exclusive_builds.prf \
		/opt/VA/Qt-5.6.3/mkspecs/features/default_pre.prf \
		deployment.pri \
		/opt/VA/Qt-5.6.3/mkspecs/features/resolve_config.prf \
		/opt/VA/Qt-5.6.3/mkspecs/features/default_post.prf \
		/opt/VA/Qt-5.6.3/mkspecs/features/qml_debug.prf \
		/opt/VA/Qt-5.6.3/mkspecs/features/declarative_debug.prf \
		/opt/VA/Qt-5.6.3/mkspecs/features/warn_on.prf \
		/opt/VA/Qt-5.6.3/mkspecs/features/qt.prf \
		/opt/VA/Qt-5.6.3/mkspecs/features/resources.prf \
		/opt/VA/Qt-5.6.3/mkspecs/features/moc.prf \
		/opt/VA/Qt-5.6.3/mkspecs/features/unix/opengl.prf \
		/opt/VA/Qt-5.6.3/mkspecs/features/uic.prf \
		/opt/VA/Qt-5.6.3/mkspecs/features/unix/thread.prf \
		/opt/VA/Qt-5.6.3/mkspecs/features/file_copies.prf \
		/opt/VA/Qt-5.6.3/mkspecs/features/testcase_targets.prf \
		/opt/VA/Qt-5.6.3/mkspecs/features/exceptions.prf \
		/opt/VA/Qt-5.6.3/mkspecs/features/yacc.prf \
		/opt/VA/Qt-5.6.3/mkspecs/features/lex.prf \
		kr_ccpilot_va.pro \
		qml.qrc \
		/opt/VA/Qt-5.6.3/lib/libQt5Quick.prl \
		/opt/VA/Qt-5.6.3/lib/libQt5Widgets.prl \
		/opt/VA/Qt-5.6.3/lib/libQt5Gui.prl \
		/opt/VA/Qt-5.6.3/lib/libQt5Qml.prl \
		/opt/VA/Qt-5.6.3/lib/libQt5Network.prl \
		/opt/VA/Qt-5.6.3/lib/libQt5Core.prl
	$(QMAKE) -spec linux-arm-none-gnueabi-g++ CONFIG+=debug CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile kr_ccpilot_va.pro
/opt/VA/Qt-5.6.3/mkspecs/features/spec_pre.prf:
/opt/VA/Qt-5.6.3/mkspecs/common/unix.conf:
/opt/VA/Qt-5.6.3/mkspecs/common/linux.conf:
/opt/VA/Qt-5.6.3/mkspecs/common/sanitize.conf:
/opt/VA/Qt-5.6.3/mkspecs/common/gcc-base.conf:
/opt/VA/Qt-5.6.3/mkspecs/common/gcc-base-unix.conf:
/opt/VA/Qt-5.6.3/mkspecs/common/g++-base.conf:
/opt/VA/Qt-5.6.3/mkspecs/common/g++-unix.conf:
/opt/VA/Qt-5.6.3/mkspecs/qconfig.pri:
/opt/VA/Qt-5.6.3/mkspecs/modules/qt_lib_3dcore.pri:
/opt/VA/Qt-5.6.3/mkspecs/modules/qt_lib_3dcore_private.pri:
/opt/VA/Qt-5.6.3/mkspecs/modules/qt_lib_3dinput.pri:
/opt/VA/Qt-5.6.3/mkspecs/modules/qt_lib_3dinput_private.pri:
/opt/VA/Qt-5.6.3/mkspecs/modules/qt_lib_3dlogic.pri:
/opt/VA/Qt-5.6.3/mkspecs/modules/qt_lib_3dlogic_private.pri:
/opt/VA/Qt-5.6.3/mkspecs/modules/qt_lib_3dquick.pri:
/opt/VA/Qt-5.6.3/mkspecs/modules/qt_lib_3dquick_private.pri:
/opt/VA/Qt-5.6.3/mkspecs/modules/qt_lib_3dquickinput.pri:
/opt/VA/Qt-5.6.3/mkspecs/modules/qt_lib_3dquickinput_private.pri:
/opt/VA/Qt-5.6.3/mkspecs/modules/qt_lib_3dquickrender.pri:
/opt/VA/Qt-5.6.3/mkspecs/modules/qt_lib_3dquickrender_private.pri:
/opt/VA/Qt-5.6.3/mkspecs/modules/qt_lib_3drender.pri:
/opt/VA/Qt-5.6.3/mkspecs/modules/qt_lib_3drender_private.pri:
/opt/VA/Qt-5.6.3/mkspecs/modules/qt_lib_bluetooth.pri:
/opt/VA/Qt-5.6.3/mkspecs/modules/qt_lib_bluetooth_private.pri:
/opt/VA/Qt-5.6.3/mkspecs/modules/qt_lib_bootstrap_private.pri:
/opt/VA/Qt-5.6.3/mkspecs/modules/qt_lib_clucene_private.pri:
/opt/VA/Qt-5.6.3/mkspecs/modules/qt_lib_concurrent.pri:
/opt/VA/Qt-5.6.3/mkspecs/modules/qt_lib_concurrent_private.pri:
/opt/VA/Qt-5.6.3/mkspecs/modules/qt_lib_core.pri:
/opt/VA/Qt-5.6.3/mkspecs/modules/qt_lib_core_private.pri:
/opt/VA/Qt-5.6.3/mkspecs/modules/qt_lib_dbus.pri:
/opt/VA/Qt-5.6.3/mkspecs/modules/qt_lib_dbus_private.pri:
/opt/VA/Qt-5.6.3/mkspecs/modules/qt_lib_eglfs_device_lib_private.pri:
/opt/VA/Qt-5.6.3/mkspecs/modules/qt_lib_enginio.pri:
/opt/VA/Qt-5.6.3/mkspecs/modules/qt_lib_enginio_private.pri:
/opt/VA/Qt-5.6.3/mkspecs/modules/qt_lib_gui.pri:
/opt/VA/Qt-5.6.3/mkspecs/modules/qt_lib_gui_private.pri:
/opt/VA/Qt-5.6.3/mkspecs/modules/qt_lib_help.pri:
/opt/VA/Qt-5.6.3/mkspecs/modules/qt_lib_help_private.pri:
/opt/VA/Qt-5.6.3/mkspecs/modules/qt_lib_labscontrols_private.pri:
/opt/VA/Qt-5.6.3/mkspecs/modules/qt_lib_labstemplates_private.pri:
/opt/VA/Qt-5.6.3/mkspecs/modules/qt_lib_location.pri:
/opt/VA/Qt-5.6.3/mkspecs/modules/qt_lib_location_private.pri:
/opt/VA/Qt-5.6.3/mkspecs/modules/qt_lib_multimedia.pri:
/opt/VA/Qt-5.6.3/mkspecs/modules/qt_lib_multimedia_private.pri:
/opt/VA/Qt-5.6.3/mkspecs/modules/qt_lib_multimediawidgets.pri:
/opt/VA/Qt-5.6.3/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
/opt/VA/Qt-5.6.3/mkspecs/modules/qt_lib_network.pri:
/opt/VA/Qt-5.6.3/mkspecs/modules/qt_lib_network_private.pri:
/opt/VA/Qt-5.6.3/mkspecs/modules/qt_lib_nfc.pri:
/opt/VA/Qt-5.6.3/mkspecs/modules/qt_lib_nfc_private.pri:
/opt/VA/Qt-5.6.3/mkspecs/modules/qt_lib_opengl.pri:
/opt/VA/Qt-5.6.3/mkspecs/modules/qt_lib_opengl_private.pri:
/opt/VA/Qt-5.6.3/mkspecs/modules/qt_lib_openglextensions.pri:
/opt/VA/Qt-5.6.3/mkspecs/modules/qt_lib_openglextensions_private.pri:
/opt/VA/Qt-5.6.3/mkspecs/modules/qt_lib_platformsupport_private.pri:
/opt/VA/Qt-5.6.3/mkspecs/modules/qt_lib_positioning.pri:
/opt/VA/Qt-5.6.3/mkspecs/modules/qt_lib_positioning_private.pri:
/opt/VA/Qt-5.6.3/mkspecs/modules/qt_lib_printsupport.pri:
/opt/VA/Qt-5.6.3/mkspecs/modules/qt_lib_printsupport_private.pri:
/opt/VA/Qt-5.6.3/mkspecs/modules/qt_lib_qml.pri:
/opt/VA/Qt-5.6.3/mkspecs/modules/qt_lib_qml_private.pri:
/opt/VA/Qt-5.6.3/mkspecs/modules/qt_lib_qmldevtools_private.pri:
/opt/VA/Qt-5.6.3/mkspecs/modules/qt_lib_qmltest.pri:
/opt/VA/Qt-5.6.3/mkspecs/modules/qt_lib_qmltest_private.pri:
/opt/VA/Qt-5.6.3/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
/opt/VA/Qt-5.6.3/mkspecs/modules/qt_lib_quick.pri:
/opt/VA/Qt-5.6.3/mkspecs/modules/qt_lib_quick_private.pri:
/opt/VA/Qt-5.6.3/mkspecs/modules/qt_lib_quickparticles_private.pri:
/opt/VA/Qt-5.6.3/mkspecs/modules/qt_lib_quickwidgets.pri:
/opt/VA/Qt-5.6.3/mkspecs/modules/qt_lib_quickwidgets_private.pri:
/opt/VA/Qt-5.6.3/mkspecs/modules/qt_lib_script.pri:
/opt/VA/Qt-5.6.3/mkspecs/modules/qt_lib_script_private.pri:
/opt/VA/Qt-5.6.3/mkspecs/modules/qt_lib_scripttools.pri:
/opt/VA/Qt-5.6.3/mkspecs/modules/qt_lib_scripttools_private.pri:
/opt/VA/Qt-5.6.3/mkspecs/modules/qt_lib_sensors.pri:
/opt/VA/Qt-5.6.3/mkspecs/modules/qt_lib_sensors_private.pri:
/opt/VA/Qt-5.6.3/mkspecs/modules/qt_lib_serialport.pri:
/opt/VA/Qt-5.6.3/mkspecs/modules/qt_lib_serialport_private.pri:
/opt/VA/Qt-5.6.3/mkspecs/modules/qt_lib_sql.pri:
/opt/VA/Qt-5.6.3/mkspecs/modules/qt_lib_sql_private.pri:
/opt/VA/Qt-5.6.3/mkspecs/modules/qt_lib_svg.pri:
/opt/VA/Qt-5.6.3/mkspecs/modules/qt_lib_svg_private.pri:
/opt/VA/Qt-5.6.3/mkspecs/modules/qt_lib_testlib.pri:
/opt/VA/Qt-5.6.3/mkspecs/modules/qt_lib_testlib_private.pri:
/opt/VA/Qt-5.6.3/mkspecs/modules/qt_lib_uiplugin.pri:
/opt/VA/Qt-5.6.3/mkspecs/modules/qt_lib_uitools.pri:
/opt/VA/Qt-5.6.3/mkspecs/modules/qt_lib_uitools_private.pri:
/opt/VA/Qt-5.6.3/mkspecs/modules/qt_lib_webchannel.pri:
/opt/VA/Qt-5.6.3/mkspecs/modules/qt_lib_webchannel_private.pri:
/opt/VA/Qt-5.6.3/mkspecs/modules/qt_lib_websockets.pri:
/opt/VA/Qt-5.6.3/mkspecs/modules/qt_lib_websockets_private.pri:
/opt/VA/Qt-5.6.3/mkspecs/modules/qt_lib_widgets.pri:
/opt/VA/Qt-5.6.3/mkspecs/modules/qt_lib_widgets_private.pri:
/opt/VA/Qt-5.6.3/mkspecs/modules/qt_lib_xml.pri:
/opt/VA/Qt-5.6.3/mkspecs/modules/qt_lib_xml_private.pri:
/opt/VA/Qt-5.6.3/mkspecs/modules/qt_lib_xmlpatterns.pri:
/opt/VA/Qt-5.6.3/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
/opt/VA/Qt-5.6.3/mkspecs/modules/qt_lib_zlib_private.pri:
/opt/VA/Qt-5.6.3/mkspecs/features/qt_functions.prf:
/opt/VA/Qt-5.6.3/mkspecs/features/qt_config.prf:
/opt/VA/Qt-5.6.3/mkspecs/linux-arm-none-gnueabi-g++/qmake.conf:
/opt/VA/Qt-5.6.3/mkspecs/features/spec_post.prf:
/opt/VA/Qt-5.6.3/mkspecs/features/exclusive_builds.prf:
/opt/VA/Qt-5.6.3/mkspecs/features/default_pre.prf:
deployment.pri:
/opt/VA/Qt-5.6.3/mkspecs/features/resolve_config.prf:
/opt/VA/Qt-5.6.3/mkspecs/features/default_post.prf:
/opt/VA/Qt-5.6.3/mkspecs/features/qml_debug.prf:
/opt/VA/Qt-5.6.3/mkspecs/features/declarative_debug.prf:
/opt/VA/Qt-5.6.3/mkspecs/features/warn_on.prf:
/opt/VA/Qt-5.6.3/mkspecs/features/qt.prf:
/opt/VA/Qt-5.6.3/mkspecs/features/resources.prf:
/opt/VA/Qt-5.6.3/mkspecs/features/moc.prf:
/opt/VA/Qt-5.6.3/mkspecs/features/unix/opengl.prf:
/opt/VA/Qt-5.6.3/mkspecs/features/uic.prf:
/opt/VA/Qt-5.6.3/mkspecs/features/unix/thread.prf:
/opt/VA/Qt-5.6.3/mkspecs/features/file_copies.prf:
/opt/VA/Qt-5.6.3/mkspecs/features/testcase_targets.prf:
/opt/VA/Qt-5.6.3/mkspecs/features/exceptions.prf:
/opt/VA/Qt-5.6.3/mkspecs/features/yacc.prf:
/opt/VA/Qt-5.6.3/mkspecs/features/lex.prf:
kr_ccpilot_va.pro:
qml.qrc:
/opt/VA/Qt-5.6.3/lib/libQt5Quick.prl:
/opt/VA/Qt-5.6.3/lib/libQt5Widgets.prl:
/opt/VA/Qt-5.6.3/lib/libQt5Gui.prl:
/opt/VA/Qt-5.6.3/lib/libQt5Qml.prl:
/opt/VA/Qt-5.6.3/lib/libQt5Network.prl:
/opt/VA/Qt-5.6.3/lib/libQt5Core.prl:
qmake: FORCE
	@$(QMAKE) -spec linux-arm-none-gnueabi-g++ CONFIG+=debug CONFIG+=declarative_debug CONFIG+=qml_debug -o Makefile kr_ccpilot_va.pro

qmake_all: FORCE


all: Makefile $(TARGET)

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents qml.qrc $(DISTDIR)/
	$(COPY_FILE) --parents pulu.h $(DISTDIR)/
	$(COPY_FILE) --parents main.cpp pulu.cpp $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all: qrc_qml.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_qml.cpp
qrc_qml.cpp: qml.qrc \
		qml/main.qml
	/opt/VA/Qt-5.6.3/bin/rcc -name qml qml.qrc -o qrc_qml.cpp

compiler_moc_header_make_all: moc_pulu.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_pulu.cpp
moc_pulu.cpp: /opt/VA/Qt-5.6.3/include/QtCore/QObject \
		/opt/VA/Qt-5.6.3/include/QtCore/qobject.h \
		/opt/VA/Qt-5.6.3/include/QtCore/qobjectdefs.h \
		/opt/VA/Qt-5.6.3/include/QtCore/qnamespace.h \
		/opt/VA/Qt-5.6.3/include/QtCore/qglobal.h \
		/opt/VA/Qt-5.6.3/include/QtCore/qconfig.h \
		/opt/VA/Qt-5.6.3/include/QtCore/qfeatures.h \
		/opt/VA/Qt-5.6.3/include/QtCore/qsystemdetection.h \
		/opt/VA/Qt-5.6.3/include/QtCore/qprocessordetection.h \
		/opt/VA/Qt-5.6.3/include/QtCore/qcompilerdetection.h \
		/opt/VA/Qt-5.6.3/include/QtCore/qtypeinfo.h \
		/opt/VA/Qt-5.6.3/include/QtCore/qtypetraits.h \
		/opt/VA/Qt-5.6.3/include/QtCore/qisenum.h \
		/opt/VA/Qt-5.6.3/include/QtCore/qsysinfo.h \
		/opt/VA/Qt-5.6.3/include/QtCore/qlogging.h \
		/opt/VA/Qt-5.6.3/include/QtCore/qflags.h \
		/opt/VA/Qt-5.6.3/include/QtCore/qatomic.h \
		/opt/VA/Qt-5.6.3/include/QtCore/qbasicatomic.h \
		/opt/VA/Qt-5.6.3/include/QtCore/qatomic_bootstrap.h \
		/opt/VA/Qt-5.6.3/include/QtCore/qgenericatomic.h \
		/opt/VA/Qt-5.6.3/include/QtCore/qatomic_cxx11.h \
		/opt/VA/Qt-5.6.3/include/QtCore/qatomic_gcc.h \
		/opt/VA/Qt-5.6.3/include/QtCore/qatomic_msvc.h \
		/opt/VA/Qt-5.6.3/include/QtCore/qatomic_armv7.h \
		/opt/VA/Qt-5.6.3/include/QtCore/qatomic_armv6.h \
		/opt/VA/Qt-5.6.3/include/QtCore/qatomic_armv5.h \
		/opt/VA/Qt-5.6.3/include/QtCore/qatomic_ia64.h \
		/opt/VA/Qt-5.6.3/include/QtCore/qatomic_x86.h \
		/opt/VA/Qt-5.6.3/include/QtCore/qatomic_unix.h \
		/opt/VA/Qt-5.6.3/include/QtCore/qglobalstatic.h \
		/opt/VA/Qt-5.6.3/include/QtCore/qmutex.h \
		/opt/VA/Qt-5.6.3/include/QtCore/qnumeric.h \
		/opt/VA/Qt-5.6.3/include/QtCore/qversiontagging.h \
		/opt/VA/Qt-5.6.3/include/QtCore/qobjectdefs_impl.h \
		/opt/VA/Qt-5.6.3/include/QtCore/qstring.h \
		/opt/VA/Qt-5.6.3/include/QtCore/qchar.h \
		/opt/VA/Qt-5.6.3/include/QtCore/qbytearray.h \
		/opt/VA/Qt-5.6.3/include/QtCore/qrefcount.h \
		/opt/VA/Qt-5.6.3/include/QtCore/qarraydata.h \
		/opt/VA/usr/include/string.h \
		/opt/VA/usr/include/features.h \
		/opt/VA/usr/include/bits/predefs.h \
		/opt/VA/usr/include/sys/cdefs.h \
		/opt/VA/usr/include/bits/wordsize.h \
		/opt/VA/usr/include/gnu/stubs.h \
		/opt/VA/usr/include/xlocale.h \
		/opt/VA/usr/include/bits/string.h \
		/opt/VA/usr/include/bits/string2.h \
		/opt/VA/usr/include/endian.h \
		/opt/VA/usr/include/bits/endian.h \
		/opt/VA/usr/include/bits/byteswap.h \
		/opt/VA/usr/include/bits/types.h \
		/opt/VA/usr/include/bits/typesizes.h \
		/opt/VA/usr/include/stdlib.h \
		/opt/VA/usr/include/bits/waitflags.h \
		/opt/VA/usr/include/bits/waitstatus.h \
		/opt/VA/usr/include/sys/types.h \
		/opt/VA/usr/include/time.h \
		/opt/VA/usr/include/bits/time.h \
		/opt/VA/usr/include/sys/select.h \
		/opt/VA/usr/include/bits/select.h \
		/opt/VA/usr/include/bits/sigset.h \
		/opt/VA/usr/include/sys/sysmacros.h \
		/opt/VA/usr/include/bits/pthreadtypes.h \
		/opt/VA/usr/include/alloca.h \
		/opt/VA/usr/include/bits/stdlib.h \
		/opt/VA/usr/include/bits/stdlib-ldbl.h \
		/opt/VA/usr/include/bits/string3.h \
		/opt/VA/Qt-5.6.3/include/QtCore/qstringbuilder.h \
		/opt/VA/Qt-5.6.3/include/QtCore/qlist.h \
		/opt/VA/Qt-5.6.3/include/QtCore/qalgorithms.h \
		/opt/VA/Qt-5.6.3/include/QtCore/qiterator.h \
		/opt/VA/Qt-5.6.3/include/QtCore/qhashfunctions.h \
		/opt/VA/Qt-5.6.3/include/QtCore/qpair.h \
		/opt/VA/usr/include/limits.h \
		/opt/VA/usr/include/bits/posix1_lim.h \
		/opt/VA/usr/include/bits/local_lim.h \
		/opt/VA/usr/include/linux/limits.h \
		/opt/VA/usr/include/bits/posix2_lim.h \
		/opt/VA/usr/include/bits/xopen_lim.h \
		/opt/VA/usr/include/bits/stdio_lim.h \
		/opt/VA/Qt-5.6.3/include/QtCore/qbytearraylist.h \
		/opt/VA/Qt-5.6.3/include/QtCore/qstringlist.h \
		/opt/VA/Qt-5.6.3/include/QtCore/qregexp.h \
		/opt/VA/Qt-5.6.3/include/QtCore/qstringmatcher.h \
		/opt/VA/Qt-5.6.3/include/QtCore/qcoreevent.h \
		/opt/VA/Qt-5.6.3/include/QtCore/qscopedpointer.h \
		/opt/VA/Qt-5.6.3/include/QtCore/qmetatype.h \
		/opt/VA/Qt-5.6.3/include/QtCore/qvarlengtharray.h \
		/opt/VA/Qt-5.6.3/include/QtCore/qcontainerfwd.h \
		/opt/VA/Qt-5.6.3/include/QtCore/qobject_impl.h \
		pulu.h
	/opt/VA/Qt-5.6.3/bin/moc $(DEFINES) -I/opt/VA/Qt-5.6.3/mkspecs/linux-arm-none-gnueabi-g++ -I/home/ccs/qt/MyProjects/kr_ccpilot_va -I/opt/VA/Qt-5.6.3/include -I/opt/VA/Qt-5.6.3/include/QtQuick -I/opt/VA/Qt-5.6.3/include/QtWidgets -I/opt/VA/Qt-5.6.3/include/QtGui -I/opt/VA/Qt-5.6.3/include/QtQml -I/opt/VA/Qt-5.6.3/include/QtNetwork -I/opt/VA/Qt-5.6.3/include/QtCore -I/opt/codesourcery/arm-none-linux-gnueabi/include/c++/4.6.1 -I/opt/codesourcery/arm-none-linux-gnueabi/include/c++/4.6.1/arm-none-linux-gnueabi -I/opt/codesourcery/arm-none-linux-gnueabi/include/c++/4.6.1/backward -I/opt/codesourcery/lib/gcc/arm-none-linux-gnueabi/4.6.1/include -I/opt/codesourcery/lib/gcc/arm-none-linux-gnueabi/4.6.1/include-fixed -I/opt/codesourcery/arm-none-linux-gnueabi/include -I/opt/codesourcery/arm-none-linux-gnueabi/libc/usr/include pulu.h -o moc_pulu.cpp

compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_rcc_clean compiler_moc_header_clean 

####### Compile

main.o: main.cpp /opt/VA/Qt-5.6.3/include/QtWidgets/QApplication \
		/opt/VA/Qt-5.6.3/include/QtWidgets/qapplication.h \
		/opt/VA/Qt-5.6.3/include/QtCore/qcoreapplication.h \
		/opt/VA/Qt-5.6.3/include/QtCore/qglobal.h \
		/opt/VA/Qt-5.6.3/include/QtCore/qconfig.h \
		/opt/VA/Qt-5.6.3/include/QtCore/qfeatures.h \
		/opt/VA/Qt-5.6.3/include/QtCore/qsystemdetection.h \
		/opt/VA/Qt-5.6.3/include/QtCore/qprocessordetection.h \
		/opt/VA/Qt-5.6.3/include/QtCore/qcompilerdetection.h \
		/opt/VA/Qt-5.6.3/include/QtCore/qtypeinfo.h \
		/opt/VA/Qt-5.6.3/include/QtCore/qtypetraits.h \
		/opt/VA/Qt-5.6.3/include/QtCore/qisenum.h \
		/opt/VA/Qt-5.6.3/include/QtCore/qsysinfo.h \
		/opt/VA/Qt-5.6.3/include/QtCore/qlogging.h \
		/opt/VA/Qt-5.6.3/include/QtCore/qflags.h \
		/opt/VA/Qt-5.6.3/include/QtCore/qatomic.h \
		/opt/VA/Qt-5.6.3/include/QtCore/qbasicatomic.h \
		/opt/VA/Qt-5.6.3/include/QtCore/qatomic_bootstrap.h \
		/opt/VA/Qt-5.6.3/include/QtCore/qgenericatomic.h \
		/opt/VA/Qt-5.6.3/include/QtCore/qatomic_cxx11.h \
		/opt/VA/Qt-5.6.3/include/QtCore/qatomic_gcc.h \
		/opt/VA/Qt-5.6.3/include/QtCore/qatomic_msvc.h \
		/opt/VA/Qt-5.6.3/include/QtCore/qatomic_armv7.h \
		/opt/VA/Qt-5.6.3/include/QtCore/qatomic_armv6.h \
		/opt/VA/Qt-5.6.3/include/QtCore/qatomic_armv5.h \
		/opt/VA/Qt-5.6.3/include/QtCore/qatomic_ia64.h \
		/opt/VA/Qt-5.6.3/include/QtCore/qatomic_x86.h \
		/opt/VA/Qt-5.6.3/include/QtCore/qatomic_unix.h \
		/opt/VA/Qt-5.6.3/include/QtCore/qglobalstatic.h \
		/opt/VA/Qt-5.6.3/include/QtCore/qmutex.h \
		/opt/VA/Qt-5.6.3/include/QtCore/qnumeric.h \
		/opt/VA/Qt-5.6.3/include/QtCore/qversiontagging.h \
		/opt/VA/Qt-5.6.3/include/QtCore/qstring.h \
		/opt/VA/Qt-5.6.3/include/QtCore/qchar.h \
		/opt/VA/Qt-5.6.3/include/QtCore/qbytearray.h \
		/opt/VA/Qt-5.6.3/include/QtCore/qrefcount.h \
		/opt/VA/Qt-5.6.3/include/QtCore/qnamespace.h \
		/opt/VA/Qt-5.6.3/include/QtCore/qarraydata.h \
		/opt/VA/usr/include/string.h \
		/opt/VA/usr/include/features.h \
		/opt/VA/usr/include/bits/predefs.h \
		/opt/VA/usr/include/sys/cdefs.h \
		/opt/VA/usr/include/bits/wordsize.h \
		/opt/VA/usr/include/gnu/stubs.h \
		/opt/VA/usr/include/xlocale.h \
		/opt/VA/usr/include/bits/string.h \
		/opt/VA/usr/include/bits/string2.h \
		/opt/VA/usr/include/endian.h \
		/opt/VA/usr/include/bits/endian.h \
		/opt/VA/usr/include/bits/byteswap.h \
		/opt/VA/usr/include/bits/types.h \
		/opt/VA/usr/include/bits/typesizes.h \
		/opt/VA/usr/include/stdlib.h \
		/opt/VA/usr/include/bits/waitflags.h \
		/opt/VA/usr/include/bits/waitstatus.h \
		/opt/VA/usr/include/sys/types.h \
		/opt/VA/usr/include/time.h \
		/opt/VA/usr/include/bits/time.h \
		/opt/VA/usr/include/sys/select.h \
		/opt/VA/usr/include/bits/select.h \
		/opt/VA/usr/include/bits/sigset.h \
		/opt/VA/usr/include/sys/sysmacros.h \
		/opt/VA/usr/include/bits/pthreadtypes.h \
		/opt/VA/usr/include/alloca.h \
		/opt/VA/usr/include/bits/stdlib.h \
		/opt/VA/usr/include/bits/stdlib-ldbl.h \
		/opt/VA/usr/include/bits/string3.h \
		/opt/VA/Qt-5.6.3/include/QtCore/qstringbuilder.h \
		/opt/VA/Qt-5.6.3/include/QtCore/qobject.h \
		/opt/VA/Qt-5.6.3/include/QtCore/qobjectdefs.h \
		/opt/VA/Qt-5.6.3/include/QtCore/qobjectdefs_impl.h \
		/opt/VA/Qt-5.6.3/include/QtCore/qlist.h \
		/opt/VA/Qt-5.6.3/include/QtCore/qalgorithms.h \
		/opt/VA/Qt-5.6.3/include/QtCore/qiterator.h \
		/opt/VA/Qt-5.6.3/include/QtCore/qhashfunctions.h \
		/opt/VA/Qt-5.6.3/include/QtCore/qpair.h \
		/opt/VA/usr/include/limits.h \
		/opt/VA/usr/include/bits/posix1_lim.h \
		/opt/VA/usr/include/bits/local_lim.h \
		/opt/VA/usr/include/linux/limits.h \
		/opt/VA/usr/include/bits/posix2_lim.h \
		/opt/VA/usr/include/bits/xopen_lim.h \
		/opt/VA/usr/include/bits/stdio_lim.h \
		/opt/VA/Qt-5.6.3/include/QtCore/qbytearraylist.h \
		/opt/VA/Qt-5.6.3/include/QtCore/qstringlist.h \
		/opt/VA/Qt-5.6.3/include/QtCore/qregexp.h \
		/opt/VA/Qt-5.6.3/include/QtCore/qstringmatcher.h \
		/opt/VA/Qt-5.6.3/include/QtCore/qcoreevent.h \
		/opt/VA/Qt-5.6.3/include/QtCore/qscopedpointer.h \
		/opt/VA/Qt-5.6.3/include/QtCore/qmetatype.h \
		/opt/VA/Qt-5.6.3/include/QtCore/qvarlengtharray.h \
		/opt/VA/Qt-5.6.3/include/QtCore/qcontainerfwd.h \
		/opt/VA/Qt-5.6.3/include/QtCore/qobject_impl.h \
		/opt/VA/Qt-5.6.3/include/QtCore/qeventloop.h \
		/opt/VA/Qt-5.6.3/include/QtGui/qwindowdefs.h \
		/opt/VA/Qt-5.6.3/include/QtGui/qwindowdefs_win.h \
		/opt/VA/Qt-5.6.3/include/QtCore/qpoint.h \
		/opt/VA/Qt-5.6.3/include/QtCore/qsize.h \
		/opt/VA/Qt-5.6.3/include/QtGui/qcursor.h \
		/opt/VA/Qt-5.6.3/include/QtWidgets/qdesktopwidget.h \
		/opt/VA/Qt-5.6.3/include/QtWidgets/qwidget.h \
		/opt/VA/Qt-5.6.3/include/QtCore/qmargins.h \
		/opt/VA/Qt-5.6.3/include/QtGui/qpaintdevice.h \
		/opt/VA/Qt-5.6.3/include/QtCore/qrect.h \
		/opt/VA/Qt-5.6.3/include/QtGui/qpalette.h \
		/opt/VA/Qt-5.6.3/include/QtGui/qcolor.h \
		/opt/VA/Qt-5.6.3/include/QtGui/qrgb.h \
		/opt/VA/Qt-5.6.3/include/QtGui/qrgba64.h \
		/opt/VA/Qt-5.6.3/include/QtGui/qbrush.h \
		/opt/VA/Qt-5.6.3/include/QtCore/qvector.h \
		/opt/VA/Qt-5.6.3/include/QtGui/qmatrix.h \
		/opt/VA/Qt-5.6.3/include/QtGui/qpolygon.h \
		/opt/VA/Qt-5.6.3/include/QtGui/qregion.h \
		/opt/VA/Qt-5.6.3/include/QtCore/qdatastream.h \
		/opt/VA/Qt-5.6.3/include/QtCore/qiodevice.h \
		/opt/VA/Qt-5.6.3/include/QtCore/qline.h \
		/opt/VA/Qt-5.6.3/include/QtGui/qtransform.h \
		/opt/VA/Qt-5.6.3/include/QtGui/qpainterpath.h \
		/opt/VA/Qt-5.6.3/include/QtGui/qimage.h \
		/opt/VA/Qt-5.6.3/include/QtGui/qpixelformat.h \
		/opt/VA/Qt-5.6.3/include/QtGui/qpixmap.h \
		/opt/VA/Qt-5.6.3/include/QtCore/qsharedpointer.h \
		/opt/VA/Qt-5.6.3/include/QtCore/qshareddata.h \
		/opt/VA/Qt-5.6.3/include/QtCore/qhash.h \
		/opt/VA/Qt-5.6.3/include/QtCore/qsharedpointer_impl.h \
		/opt/VA/Qt-5.6.3/include/QtGui/qfont.h \
		/opt/VA/Qt-5.6.3/include/QtGui/qfontmetrics.h \
		/opt/VA/Qt-5.6.3/include/QtGui/qfontinfo.h \
		/opt/VA/Qt-5.6.3/include/QtWidgets/qsizepolicy.h \
		/opt/VA/Qt-5.6.3/include/QtGui/qkeysequence.h \
		/opt/VA/Qt-5.6.3/include/QtGui/qevent.h \
		/opt/VA/Qt-5.6.3/include/QtCore/qvariant.h \
		/opt/VA/Qt-5.6.3/include/QtCore/qmap.h \
		/opt/VA/Qt-5.6.3/include/QtCore/qdebug.h \
		/opt/VA/Qt-5.6.3/include/QtCore/qtextstream.h \
		/opt/VA/Qt-5.6.3/include/QtCore/qlocale.h \
		/opt/VA/usr/include/stdio.h \
		/opt/VA/usr/include/libio.h \
		/opt/VA/usr/include/_G_config.h \
		/opt/VA/usr/include/wchar.h \
		/opt/VA/usr/include/bits/wchar.h \
		/opt/VA/usr/include/wctype.h \
		/opt/VA/usr/include/bits/wchar2.h \
		/opt/VA/usr/include/bits/wchar-ldbl.h \
		/opt/VA/usr/include/gconv.h \
		/opt/VA/usr/include/bits/stdio-lock.h \
		/opt/VA/usr/include/bits/libc-lock.h \
		/opt/VA/usr/include/pthread.h \
		/opt/VA/usr/include/sched.h \
		/opt/VA/usr/include/bits/sched.h \
		/opt/VA/usr/include/bits/setjmp.h \
		/opt/VA/usr/include/errno.h \
		/opt/VA/usr/include/bits/errno.h \
		/opt/VA/usr/include/linux/errno.h \
		/opt/VA/usr/include/asm/errno.h \
		/opt/VA/usr/include/asm-generic/errno.h \
		/opt/VA/usr/include/asm-generic/errno-base.h \
		/opt/VA/usr/include/gnu/option-groups.h \
		/opt/VA/usr/include/bits/libio-ldbl.h \
		/opt/VA/usr/include/bits/sys_errlist.h \
		/opt/VA/usr/include/getopt.h \
		/opt/VA/usr/include/ctype.h \
		/opt/VA/usr/include/bits/stdio.h \
		/opt/VA/usr/include/bits/stdio2.h \
		/opt/VA/usr/include/bits/stdio-ldbl.h \
		/opt/VA/Qt-5.6.3/include/QtCore/qset.h \
		/opt/VA/Qt-5.6.3/include/QtCore/qcontiguouscache.h \
		/opt/VA/Qt-5.6.3/include/QtCore/qurl.h \
		/opt/VA/Qt-5.6.3/include/QtCore/qurlquery.h \
		/opt/VA/Qt-5.6.3/include/QtCore/qfile.h \
		/opt/VA/Qt-5.6.3/include/QtCore/qfiledevice.h \
		/opt/VA/Qt-5.6.3/include/QtGui/qvector2d.h \
		/opt/VA/Qt-5.6.3/include/QtGui/qtouchdevice.h \
		/opt/VA/Qt-5.6.3/include/QtGui/qguiapplication.h \
		/opt/VA/Qt-5.6.3/include/QtGui/qinputmethod.h \
		/opt/VA/Qt-5.6.3/include/QtQml/QQmlApplicationEngine \
		/opt/VA/Qt-5.6.3/include/QtQml/qqmlapplicationengine.h \
		/opt/VA/Qt-5.6.3/include/QtQml/qqmlengine.h \
		/opt/VA/Qt-5.6.3/include/QtQml/qjsengine.h \
		/opt/VA/Qt-5.6.3/include/QtQml/qjsvalue.h \
		/opt/VA/Qt-5.6.3/include/QtQml/qtqmlglobal.h \
		/opt/VA/Qt-5.6.3/include/QtQml/qqmlerror.h \
		/opt/VA/Qt-5.6.3/include/QtQml/qqmldebug.h \
		/opt/VA/Qt-5.6.3/include/QtQml/QQmlContext \
		/opt/VA/Qt-5.6.3/include/QtQml/qqmlcontext.h \
		/opt/VA/Qt-5.6.3/include/QtQuick/QQuickItem \
		/opt/VA/Qt-5.6.3/include/QtQuick/qquickitem.h \
		/opt/VA/Qt-5.6.3/include/QtQuick/qtquickglobal.h \
		/opt/VA/Qt-5.6.3/include/QtQml/qqml.h \
		/opt/VA/Qt-5.6.3/include/QtQml/qqmlprivate.h \
		/opt/VA/Qt-5.6.3/include/QtQml/qqmlparserstatus.h \
		/opt/VA/Qt-5.6.3/include/QtQml/qqmlpropertyvaluesource.h \
		/opt/VA/Qt-5.6.3/include/QtQml/qqmllist.h \
		/opt/VA/Qt-5.6.3/include/QtCore/qmetaobject.h \
		/opt/VA/Qt-5.6.3/include/QtQml/qqmlcomponent.h \
		/opt/VA/Qt-5.6.3/include/QtCore/QObject \
		/opt/VA/Qt-5.6.3/include/QtCore/QList \
		/opt/VA/Qt-5.6.3/include/QtGui/qaccessible.h \
		/opt/VA/Qt-5.6.3/include/QtQml/QtQml \
		/opt/VA/Qt-5.6.3/include/QtQml/QtQmlDepends \
		/opt/VA/Qt-5.6.3/include/QtCore/QtCore \
		/opt/VA/Qt-5.6.3/include/QtCore/QtCoreDepends \
		/opt/VA/Qt-5.6.3/include/QtCore/qabstractanimation.h \
		/opt/VA/Qt-5.6.3/include/QtCore/qanimationgroup.h \
		/opt/VA/Qt-5.6.3/include/QtCore/qparallelanimationgroup.h \
		/opt/VA/Qt-5.6.3/include/QtCore/qpauseanimation.h \
		/opt/VA/Qt-5.6.3/include/QtCore/qpropertyanimation.h \
		/opt/VA/Qt-5.6.3/include/QtCore/qvariantanimation.h \
		/opt/VA/Qt-5.6.3/include/QtCore/qeasingcurve.h \
		/opt/VA/Qt-5.6.3/include/QtCore/qsequentialanimationgroup.h \
		/opt/VA/Qt-5.6.3/include/QtCore/qtextcodec.h \
		/opt/VA/Qt-5.6.3/include/QtCore/qendian.h \
		/opt/VA/Qt-5.6.3/include/QtCore/qlibraryinfo.h \
		/opt/VA/Qt-5.6.3/include/QtCore/qdatetime.h \
		/opt/VA/Qt-5.6.3/include/QtCore/qbuffer.h \
		/opt/VA/Qt-5.6.3/include/QtCore/qdir.h \
		/opt/VA/Qt-5.6.3/include/QtCore/qfileinfo.h \
		/opt/VA/Qt-5.6.3/include/QtCore/qdiriterator.h \
		/opt/VA/Qt-5.6.3/include/QtCore/qfileselector.h \
		/opt/VA/Qt-5.6.3/include/QtCore/QStringList \
		/opt/VA/Qt-5.6.3/include/QtCore/qfilesystemwatcher.h \
		/opt/VA/Qt-5.6.3/include/QtCore/qlockfile.h \
		/opt/VA/Qt-5.6.3/include/QtCore/qloggingcategory.h \
		/opt/VA/Qt-5.6.3/include/QtCore/qprocess.h \
		/opt/VA/Qt-5.6.3/include/QtCore/qresource.h \
		/opt/VA/Qt-5.6.3/include/QtCore/qsavefile.h \
		/opt/VA/Qt-5.6.3/include/QtCore/qsettings.h \
		/opt/VA/Qt-5.6.3/include/QtCore/qstandardpaths.h \
		/opt/VA/Qt-5.6.3/include/QtCore/qstorageinfo.h \
		/opt/VA/Qt-5.6.3/include/QtCore/qtemporarydir.h \
		/opt/VA/Qt-5.6.3/include/QtCore/QScopedPointer \
		/opt/VA/Qt-5.6.3/include/QtCore/qtemporaryfile.h \
		/opt/VA/Qt-5.6.3/include/QtCore/qabstractitemmodel.h \
		/opt/VA/Qt-5.6.3/include/QtCore/qabstractproxymodel.h \
		/opt/VA/Qt-5.6.3/include/QtCore/qidentityproxymodel.h \
		/opt/VA/Qt-5.6.3/include/QtCore/qitemselectionmodel.h \
		/opt/VA/Qt-5.6.3/include/QtCore/qsortfilterproxymodel.h \
		/opt/VA/Qt-5.6.3/include/QtCore/qstringlistmodel.h \
		/opt/VA/Qt-5.6.3/include/QtCore/qjsonarray.h \
		/opt/VA/Qt-5.6.3/include/QtCore/qjsonvalue.h \
		/opt/VA/Qt-5.6.3/include/QtCore/qjsondocument.h \
		/opt/VA/Qt-5.6.3/include/QtCore/qjsonobject.h \
		/opt/VA/Qt-5.6.3/include/QtCore/qabstracteventdispatcher.h \
		/opt/VA/Qt-5.6.3/include/QtCore/qabstractnativeeventfilter.h \
		/opt/VA/Qt-5.6.3/include/QtCore/qbasictimer.h \
		/opt/VA/Qt-5.6.3/include/QtCore/qmath.h \
		/opt/VA/Qt-5.6.3/include/QtCore/qmimedata.h \
		/opt/VA/Qt-5.6.3/include/QtCore/qobjectcleanuphandler.h \
		/opt/VA/Qt-5.6.3/include/QtCore/qpointer.h \
		/opt/VA/Qt-5.6.3/include/QtCore/qsharedmemory.h \
		/opt/VA/Qt-5.6.3/include/QtCore/qsignalmapper.h \
		/opt/VA/Qt-5.6.3/include/QtCore/qsocketnotifier.h \
		/opt/VA/Qt-5.6.3/include/QtCore/qsystemsemaphore.h \
		/opt/VA/Qt-5.6.3/include/QtCore/qtimer.h \
		/opt/VA/Qt-5.6.3/include/QtCore/qtranslator.h \
		/opt/VA/Qt-5.6.3/include/QtCore/qwineventnotifier.h \
		/opt/VA/Qt-5.6.3/include/QtCore/qmimedatabase.h \
		/opt/VA/Qt-5.6.3/include/QtCore/qmimetype.h \
		/opt/VA/Qt-5.6.3/include/QtCore/qfactoryinterface.h \
		/opt/VA/Qt-5.6.3/include/QtCore/qlibrary.h \
		/opt/VA/Qt-5.6.3/include/QtCore/qplugin.h \
		/opt/VA/Qt-5.6.3/include/QtCore/qpluginloader.h \
		/opt/VA/Qt-5.6.3/include/QtCore/quuid.h \
		/opt/VA/Qt-5.6.3/include/QtCore/qabstractstate.h \
		/opt/VA/Qt-5.6.3/include/QtCore/qabstracttransition.h \
		/opt/VA/Qt-5.6.3/include/QtCore/qeventtransition.h \
		/opt/VA/Qt-5.6.3/include/QtCore/qfinalstate.h \
		/opt/VA/Qt-5.6.3/include/QtCore/qhistorystate.h \
		/opt/VA/Qt-5.6.3/include/QtCore/qsignaltransition.h \
		/opt/VA/Qt-5.6.3/include/QtCore/qstate.h \
		/opt/VA/Qt-5.6.3/include/QtCore/qstatemachine.h \
		/opt/VA/Qt-5.6.3/include/QtCore/qexception.h \
		/opt/VA/Qt-5.6.3/include/QtCore/qfuture.h \
		/opt/VA/Qt-5.6.3/include/QtCore/qfutureinterface.h \
		/opt/VA/Qt-5.6.3/include/QtCore/qrunnable.h \
		/opt/VA/Qt-5.6.3/include/QtCore/qresultstore.h \
		/opt/VA/Qt-5.6.3/include/QtCore/qfuturesynchronizer.h \
		/opt/VA/Qt-5.6.3/include/QtCore/qfuturewatcher.h \
		/opt/VA/Qt-5.6.3/include/QtCore/qreadwritelock.h \
		/opt/VA/Qt-5.6.3/include/QtCore/qsemaphore.h \
		/opt/VA/Qt-5.6.3/include/QtCore/qthread.h \
		/opt/VA/Qt-5.6.3/include/QtCore/qthreadpool.h \
		/opt/VA/Qt-5.6.3/include/QtCore/qthreadstorage.h \
		/opt/VA/Qt-5.6.3/include/QtCore/qwaitcondition.h \
		/opt/VA/Qt-5.6.3/include/QtCore/qarraydataops.h \
		/opt/VA/Qt-5.6.3/include/QtCore/qarraydatapointer.h \
		/opt/VA/Qt-5.6.3/include/QtCore/qbitarray.h \
		/opt/VA/Qt-5.6.3/include/QtCore/qbytearraymatcher.h \
		/opt/VA/Qt-5.6.3/include/QtCore/qcache.h \
		/opt/VA/Qt-5.6.3/include/QtCore/qcollator.h \
		/opt/VA/Qt-5.6.3/include/QtCore/qcommandlineoption.h \
		/opt/VA/Qt-5.6.3/include/QtCore/qcommandlineparser.h \
		/opt/VA/Qt-5.6.3/include/QtCore/qcryptographichash.h \
		/opt/VA/Qt-5.6.3/include/QtCore/qelapsedtimer.h \
		/opt/VA/Qt-5.6.3/include/QtCore/qlinkedlist.h \
		/opt/VA/Qt-5.6.3/include/QtCore/qmessageauthenticationcode.h \
		/opt/VA/Qt-5.6.3/include/QtCore/qqueue.h \
		/opt/VA/Qt-5.6.3/include/QtCore/qregularexpression.h \
		/opt/VA/Qt-5.6.3/include/QtCore/qscopedvaluerollback.h \
		/opt/VA/Qt-5.6.3/include/QtCore/qstack.h \
		/opt/VA/Qt-5.6.3/include/QtCore/qtextboundaryfinder.h \
		/opt/VA/Qt-5.6.3/include/QtCore/qtimeline.h \
		/opt/VA/Qt-5.6.3/include/QtCore/qtimezone.h \
		/opt/VA/Qt-5.6.3/include/QtCore/qversionnumber.h \
		/opt/VA/Qt-5.6.3/include/QtCore/qxmlstream.h \
		/opt/VA/Qt-5.6.3/include/QtCore/qtcoreversion.h \
		/opt/VA/Qt-5.6.3/include/QtNetwork/QtNetwork \
		/opt/VA/Qt-5.6.3/include/QtNetwork/QtNetworkDepends \
		/opt/VA/Qt-5.6.3/include/QtNetwork/qabstractnetworkcache.h \
		/opt/VA/Qt-5.6.3/include/QtNetwork/qnetworkrequest.h \
		/opt/VA/Qt-5.6.3/include/QtCore/QSharedDataPointer \
		/opt/VA/Qt-5.6.3/include/QtCore/QString \
		/opt/VA/Qt-5.6.3/include/QtCore/QUrl \
		/opt/VA/Qt-5.6.3/include/QtCore/QVariant \
		/opt/VA/Qt-5.6.3/include/QtNetwork/qhttpmultipart.h \
		/opt/VA/Qt-5.6.3/include/QtCore/QByteArray \
		/opt/VA/Qt-5.6.3/include/QtCore/QIODevice \
		/opt/VA/Qt-5.6.3/include/QtNetwork/QNetworkRequest \
		/opt/VA/Qt-5.6.3/include/QtNetwork/qnetworkaccessmanager.h \
		/opt/VA/Qt-5.6.3/include/QtNetwork/QSslConfiguration \
		/opt/VA/Qt-5.6.3/include/QtNetwork/qsslconfiguration.h \
		/opt/VA/Qt-5.6.3/include/QtNetwork/qsslsocket.h \
		/opt/VA/Qt-5.6.3/include/QtNetwork/qtcpsocket.h \
		/opt/VA/Qt-5.6.3/include/QtNetwork/qabstractsocket.h \
		/opt/VA/Qt-5.6.3/include/QtNetwork/qsslerror.h \
		/opt/VA/Qt-5.6.3/include/QtNetwork/qsslcertificate.h \
		/opt/VA/Qt-5.6.3/include/QtNetwork/qssl.h \
		/opt/VA/Qt-5.6.3/include/QtCore/QFlags \
		/opt/VA/Qt-5.6.3/include/QtNetwork/QSslPreSharedKeyAuthenticator \
		/opt/VA/Qt-5.6.3/include/QtNetwork/qsslpresharedkeyauthenticator.h \
		/opt/VA/Qt-5.6.3/include/QtCore/QtGlobal \
		/opt/VA/Qt-5.6.3/include/QtCore/QMetaType \
		/opt/VA/Qt-5.6.3/include/QtNetwork/qnetworkcookie.h \
		/opt/VA/Qt-5.6.3/include/QtNetwork/qnetworkcookiejar.h \
		/opt/VA/Qt-5.6.3/include/QtNetwork/qnetworkdiskcache.h \
		/opt/VA/Qt-5.6.3/include/QtNetwork/qnetworkreply.h \
		/opt/VA/Qt-5.6.3/include/QtNetwork/QNetworkAccessManager \
		/opt/VA/Qt-5.6.3/include/QtNetwork/qnetworkconfigmanager.h \
		/opt/VA/Qt-5.6.3/include/QtNetwork/qnetworkconfiguration.h \
		/opt/VA/Qt-5.6.3/include/QtNetwork/qnetworksession.h \
		/opt/VA/Qt-5.6.3/include/QtNetwork/qnetworkinterface.h \
		/opt/VA/Qt-5.6.3/include/QtNetwork/qhostaddress.h \
		/opt/VA/Qt-5.6.3/include/QtNetwork/qauthenticator.h \
		/opt/VA/Qt-5.6.3/include/QtNetwork/qdnslookup.h \
		/opt/VA/Qt-5.6.3/include/QtNetwork/qhostinfo.h \
		/opt/VA/Qt-5.6.3/include/QtNetwork/qnetworkproxy.h \
		/opt/VA/Qt-5.6.3/include/QtNetwork/qlocalserver.h \
		/opt/VA/Qt-5.6.3/include/QtNetwork/qlocalsocket.h \
		/opt/VA/Qt-5.6.3/include/QtNetwork/qtcpserver.h \
		/opt/VA/Qt-5.6.3/include/QtNetwork/qudpsocket.h \
		/opt/VA/Qt-5.6.3/include/QtNetwork/qsslcertificateextension.h \
		/opt/VA/Qt-5.6.3/include/QtNetwork/qsslcipher.h \
		/opt/VA/Qt-5.6.3/include/QtNetwork/qsslellipticcurve.h \
		/opt/VA/Qt-5.6.3/include/QtCore/QHash \
		/opt/VA/Qt-5.6.3/include/QtNetwork/qsslkey.h \
		/opt/VA/Qt-5.6.3/include/QtNetwork/qtnetworkversion.h \
		/opt/VA/Qt-5.6.3/include/QtQml/qjsvalueiterator.h \
		/opt/VA/Qt-5.6.3/include/QtQml/qqmlabstracturlinterceptor.h \
		/opt/VA/Qt-5.6.3/include/QtQml/qqmlexpression.h \
		/opt/VA/Qt-5.6.3/include/QtQml/qqmlscriptstring.h \
		/opt/VA/Qt-5.6.3/include/QtQml/qqmlextensioninterface.h \
		/opt/VA/Qt-5.6.3/include/QtQml/qqmlextensionplugin.h \
		/opt/VA/Qt-5.6.3/include/QtQml/qqmlfile.h \
		/opt/VA/Qt-5.6.3/include/QtQml/qqmlfileselector.h \
		/opt/VA/Qt-5.6.3/include/QtQml/QQmlEngine \
		/opt/VA/Qt-5.6.3/include/QtQml/qqmlincubator.h \
		/opt/VA/Qt-5.6.3/include/QtQml/qqmlinfo.h \
		/opt/VA/Qt-5.6.3/include/QtQml/qqmlnetworkaccessmanagerfactory.h \
		/opt/VA/Qt-5.6.3/include/QtQml/qqmlproperty.h \
		/opt/VA/Qt-5.6.3/include/QtQml/qqmlpropertymap.h \
		/opt/VA/Qt-5.6.3/include/QtQml/qtqmlversion.h \
		/opt/VA/Qt-5.6.3/include/QtGui/QFontDatabase \
		/opt/VA/Qt-5.6.3/include/QtGui/qfontdatabase.h \
		pulu.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

pulu.o: pulu.cpp pulu.h \
		/opt/VA/Qt-5.6.3/include/QtCore/QObject \
		/opt/VA/Qt-5.6.3/include/QtCore/qobject.h \
		/opt/VA/Qt-5.6.3/include/QtCore/qobjectdefs.h \
		/opt/VA/Qt-5.6.3/include/QtCore/qnamespace.h \
		/opt/VA/Qt-5.6.3/include/QtCore/qglobal.h \
		/opt/VA/Qt-5.6.3/include/QtCore/qconfig.h \
		/opt/VA/Qt-5.6.3/include/QtCore/qfeatures.h \
		/opt/VA/Qt-5.6.3/include/QtCore/qsystemdetection.h \
		/opt/VA/Qt-5.6.3/include/QtCore/qprocessordetection.h \
		/opt/VA/Qt-5.6.3/include/QtCore/qcompilerdetection.h \
		/opt/VA/Qt-5.6.3/include/QtCore/qtypeinfo.h \
		/opt/VA/Qt-5.6.3/include/QtCore/qtypetraits.h \
		/opt/VA/Qt-5.6.3/include/QtCore/qisenum.h \
		/opt/VA/Qt-5.6.3/include/QtCore/qsysinfo.h \
		/opt/VA/Qt-5.6.3/include/QtCore/qlogging.h \
		/opt/VA/Qt-5.6.3/include/QtCore/qflags.h \
		/opt/VA/Qt-5.6.3/include/QtCore/qatomic.h \
		/opt/VA/Qt-5.6.3/include/QtCore/qbasicatomic.h \
		/opt/VA/Qt-5.6.3/include/QtCore/qatomic_bootstrap.h \
		/opt/VA/Qt-5.6.3/include/QtCore/qgenericatomic.h \
		/opt/VA/Qt-5.6.3/include/QtCore/qatomic_cxx11.h \
		/opt/VA/Qt-5.6.3/include/QtCore/qatomic_gcc.h \
		/opt/VA/Qt-5.6.3/include/QtCore/qatomic_msvc.h \
		/opt/VA/Qt-5.6.3/include/QtCore/qatomic_armv7.h \
		/opt/VA/Qt-5.6.3/include/QtCore/qatomic_armv6.h \
		/opt/VA/Qt-5.6.3/include/QtCore/qatomic_armv5.h \
		/opt/VA/Qt-5.6.3/include/QtCore/qatomic_ia64.h \
		/opt/VA/Qt-5.6.3/include/QtCore/qatomic_x86.h \
		/opt/VA/Qt-5.6.3/include/QtCore/qatomic_unix.h \
		/opt/VA/Qt-5.6.3/include/QtCore/qglobalstatic.h \
		/opt/VA/Qt-5.6.3/include/QtCore/qmutex.h \
		/opt/VA/Qt-5.6.3/include/QtCore/qnumeric.h \
		/opt/VA/Qt-5.6.3/include/QtCore/qversiontagging.h \
		/opt/VA/Qt-5.6.3/include/QtCore/qobjectdefs_impl.h \
		/opt/VA/Qt-5.6.3/include/QtCore/qstring.h \
		/opt/VA/Qt-5.6.3/include/QtCore/qchar.h \
		/opt/VA/Qt-5.6.3/include/QtCore/qbytearray.h \
		/opt/VA/Qt-5.6.3/include/QtCore/qrefcount.h \
		/opt/VA/Qt-5.6.3/include/QtCore/qarraydata.h \
		/opt/VA/usr/include/string.h \
		/opt/VA/usr/include/features.h \
		/opt/VA/usr/include/bits/predefs.h \
		/opt/VA/usr/include/sys/cdefs.h \
		/opt/VA/usr/include/bits/wordsize.h \
		/opt/VA/usr/include/gnu/stubs.h \
		/opt/VA/usr/include/xlocale.h \
		/opt/VA/usr/include/bits/string.h \
		/opt/VA/usr/include/bits/string2.h \
		/opt/VA/usr/include/endian.h \
		/opt/VA/usr/include/bits/endian.h \
		/opt/VA/usr/include/bits/byteswap.h \
		/opt/VA/usr/include/bits/types.h \
		/opt/VA/usr/include/bits/typesizes.h \
		/opt/VA/usr/include/stdlib.h \
		/opt/VA/usr/include/bits/waitflags.h \
		/opt/VA/usr/include/bits/waitstatus.h \
		/opt/VA/usr/include/sys/types.h \
		/opt/VA/usr/include/time.h \
		/opt/VA/usr/include/bits/time.h \
		/opt/VA/usr/include/sys/select.h \
		/opt/VA/usr/include/bits/select.h \
		/opt/VA/usr/include/bits/sigset.h \
		/opt/VA/usr/include/sys/sysmacros.h \
		/opt/VA/usr/include/bits/pthreadtypes.h \
		/opt/VA/usr/include/alloca.h \
		/opt/VA/usr/include/bits/stdlib.h \
		/opt/VA/usr/include/bits/stdlib-ldbl.h \
		/opt/VA/usr/include/bits/string3.h \
		/opt/VA/Qt-5.6.3/include/QtCore/qstringbuilder.h \
		/opt/VA/Qt-5.6.3/include/QtCore/qlist.h \
		/opt/VA/Qt-5.6.3/include/QtCore/qalgorithms.h \
		/opt/VA/Qt-5.6.3/include/QtCore/qiterator.h \
		/opt/VA/Qt-5.6.3/include/QtCore/qhashfunctions.h \
		/opt/VA/Qt-5.6.3/include/QtCore/qpair.h \
		/opt/VA/usr/include/limits.h \
		/opt/VA/usr/include/bits/posix1_lim.h \
		/opt/VA/usr/include/bits/local_lim.h \
		/opt/VA/usr/include/linux/limits.h \
		/opt/VA/usr/include/bits/posix2_lim.h \
		/opt/VA/usr/include/bits/xopen_lim.h \
		/opt/VA/usr/include/bits/stdio_lim.h \
		/opt/VA/Qt-5.6.3/include/QtCore/qbytearraylist.h \
		/opt/VA/Qt-5.6.3/include/QtCore/qstringlist.h \
		/opt/VA/Qt-5.6.3/include/QtCore/qregexp.h \
		/opt/VA/Qt-5.6.3/include/QtCore/qstringmatcher.h \
		/opt/VA/Qt-5.6.3/include/QtCore/qcoreevent.h \
		/opt/VA/Qt-5.6.3/include/QtCore/qscopedpointer.h \
		/opt/VA/Qt-5.6.3/include/QtCore/qmetatype.h \
		/opt/VA/Qt-5.6.3/include/QtCore/qvarlengtharray.h \
		/opt/VA/Qt-5.6.3/include/QtCore/qcontainerfwd.h \
		/opt/VA/Qt-5.6.3/include/QtCore/qobject_impl.h \
		/opt/VA/usr/include/stdio.h \
		/opt/VA/usr/include/libio.h \
		/opt/VA/usr/include/_G_config.h \
		/opt/VA/usr/include/wchar.h \
		/opt/VA/usr/include/bits/wchar.h \
		/opt/VA/usr/include/wctype.h \
		/opt/VA/usr/include/bits/wchar2.h \
		/opt/VA/usr/include/bits/wchar-ldbl.h \
		/opt/VA/usr/include/gconv.h \
		/opt/VA/usr/include/bits/stdio-lock.h \
		/opt/VA/usr/include/bits/libc-lock.h \
		/opt/VA/usr/include/pthread.h \
		/opt/VA/usr/include/sched.h \
		/opt/VA/usr/include/bits/sched.h \
		/opt/VA/usr/include/bits/setjmp.h \
		/opt/VA/usr/include/errno.h \
		/opt/VA/usr/include/bits/errno.h \
		/opt/VA/usr/include/linux/errno.h \
		/opt/VA/usr/include/asm/errno.h \
		/opt/VA/usr/include/asm-generic/errno.h \
		/opt/VA/usr/include/asm-generic/errno-base.h \
		/opt/VA/usr/include/gnu/option-groups.h \
		/opt/VA/usr/include/bits/libio-ldbl.h \
		/opt/VA/usr/include/bits/sys_errlist.h \
		/opt/VA/usr/include/getopt.h \
		/opt/VA/usr/include/ctype.h \
		/opt/VA/usr/include/bits/stdio.h \
		/opt/VA/usr/include/bits/stdio2.h \
		/opt/VA/usr/include/bits/stdio-ldbl.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o pulu.o pulu.cpp

qrc_qml.o: qrc_qml.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_qml.o qrc_qml.cpp

moc_pulu.o: moc_pulu.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_pulu.o moc_pulu.cpp

####### Install

install_target: first FORCE
	@test -d $(INSTALL_ROOT)/opt/kr_ccpilot_va/bin || mkdir -p $(INSTALL_ROOT)/opt/kr_ccpilot_va/bin
	-$(INSTALL_PROGRAM) $(QMAKE_TARGET) $(INSTALL_ROOT)/opt/kr_ccpilot_va/bin/$(QMAKE_TARGET)

uninstall_target: FORCE
	-$(DEL_FILE) $(INSTALL_ROOT)/opt/kr_ccpilot_va/bin/$(QMAKE_TARGET)
	-$(DEL_DIR) $(INSTALL_ROOT)/opt/kr_ccpilot_va/bin/ 


install: install_target  FORCE

uninstall: uninstall_target  FORCE

FORCE:

